### ISSUE TITLE
[Bug]: mysql reader split too many tasks ,cause too many connctions

### ISSUE THREAD

**Issue by yinlice** [wgzhao/Addax#1000]
### What happened?

mysql分库分表没有主键
autoPk:true 开启 后有这个现象.
autoPk:false 可以解决

### Version

4.1.3 (Default)

### Java JDK Version

Oracle JDK 1.8.0

**Comment by yinlice** [comment]
Addax version :: (v4.0.9-SNAPSHOT)

**Comment by wgzhao** [comment]
请给出完整的任务执行日志
