### ISSUE TITLE
[Bug]: 连接postgrsql失败

### ISSUE THREAD

**Issue by wangjiancheng180** [wgzhao/Addax#1012]
### What happened?

A bug happened!我下载的是4.1.4的版本在连接postgresql时失败了，我不清楚是什么原因

### Version

4.1.3 (Default)

### Java JDK Version

Oracle JDK 1.8.0

**Comment by wgzhao** [comment]
请给出任务执行的详细输出

**Comment by wgzhao** [comment]
从报错看，是插件无法连接数据库，请确认数据库地址以及账号密码正确，也可以尝试使用psql 命令行连接测试看看是否能连接上。

另外，输出日志请勿使用截图方式，直接粘贴日志文字为佳。

**Comment by wangjiancheng180** [comment]
> 从报错看，是插件无法连接数据库，请确认数据库地址以及账号密码正确，也可以尝试使用psql 命令行连接测试看看是否能连接上。
> 
> 另外，输出日志请勿使用截图方式，直接粘贴日志文字为佳。

我找到原因了根据远程debug发现是缺少jar包Cannot load JDBC driver class ‘org.postgresql.Driver‘；我从GitHub上下载的包发现\addax-4.1.4\plugin\reader\postgresqlreader\libs缺少依赖，我复制了一个postgresql的jdbc包就成功连接了
