### ISSUE TITLE
[Bug]: windows调试源码包方法抛出'java.lang.NoClassDefFoundError'

### ISSUE THREAD

**Issue by wangjiancheng180** [wgzhao/Addax#1013]
### What happened?

A bug happened!
![2](https://github.com/wgzhao/Addax/assets/63392742/f3c1dfe2-2196-4db1-a72d-0654b9ced5b3)
调试的是4.1.4源码，在加载插件postgresqlreader这个插件类时newInstance()时抛出了这个异常，我看到clazz是有对象的应该是找到了这个类的

### Version

4.1.3 (Default)

### Java JDK Version

Oracle JDK 1.8.0

**Comment by Bear-big-code** [comment]
在core的pom.xml中引入调试的插件即可
