### ISSUE TITLE
[help wanted]: 任务结果上报使用详细描述

### ISSUE THREAD

**Issue by Hitooooo** [wgzhao/Addax#1033]
### What happened?

![image](https://github.com/wgzhao/Addax/assets/19512047/20429d26-af1f-486b-9bb1-3f13ccdfc126)

将数据同步统计结果上传给其他服务器，这里的服务器指的是另一个Addax实例吗？可以传到自己服务器的接口吗？

### Version

4.1.3 (Default)

### OS Type

Linux (Default)

### Java JDK Version

Oracle JDK 1.8.0

**Comment by wgzhao** [comment]
传到自己的服务器，假定你填写的地址是 `http://127.0.0.1:8080/addaxReport` ,那么任务结束后，会通过 POST 方式向此结果发送以下数据

```json
{
  "jobName": "test",
  "startTimeStamp": 1587971621,
  "endTimeStamp": 1587971621,
  "totalCosts": 10,
  "byteSpeedPerSecond": 33,
  "recordSpeedPerSecond": 1,
  "totalReadRecords": 6,
  "totalErrorRecords": 0,
  "jobContent": {
    ...
  }
}
```

详情参考：<https://wgzhao.github.io/Addax/develop/statsreport/>
