### ISSUE TITLE
[question]: Support for deployment via k8s

### ISSUE THREAD

**Issue by bazooka720** [wgzhao/Addax#1039]
### What happened?

Do you support deployment on Kubernetes? 

### Version

4.1.3 (Default)

### Java JDK Version

Oracle JDK 1.8.0

**Comment by wgzhao** [comment]
Docker images are currently created for each release version, including a lite version and a full plugins version. These images can be deployed directly in a Kubernetes environment. For more information on the images, please refer to https://hub.docker.com/r/wgzhao/addax
