### ISSUE TITLE
mysqlwriter中的connection无法配置多个目标

### ISSUE THREAD

**Issue by xcmonline** [wgzhao/Addax#1066]
### What happened?

connection这个参数是允许配置多个目标源，表字段一致，但实际配置后会提示。
您的配置文件中的列配置信息有误. 您要写入的目的端的表个数是:2 , 但是根据系统建议需要切分的份数是：1. 请检查您的配置并作出修改。
这个插件能写入多个目标库吗？

### Version

4.1.3 (Default)

### Java JDK Version

Oracle JDK 1.8.0

**Comment by wgzhao** [comment]
暂不支持
