### ISSUE TITLE
有计划支持amazon redshift吗

### ISSUE THREAD

**Issue by ProjectMoss** [wgzhao/Addax#180]
目前找不到一款比较好用的redshift数据同步工具，有计划支持这个数据源吗

**Comment by wgzhao** [comment]
redshift 似乎是 presto的变种，但是我没有 redshift 服务可用，如果能够获得一个测试服务，可以加入支持中

**Comment by ProjectMoss** [comment]
新账户可以每个月免费试用750个小时。
https://aws.amazon.com/cn/redshift/free-trial/

**Comment by wgzhao** [comment]
我之前注册过，不知道还行不行，我试试看能不能薅羊毛

**Comment by ProjectMoss** [comment]
关闭
