### ISSUE TITLE
编译报错：Authorization failed for https://maven.aliyun.com/repository/public/com/google/errorprone/javac/9+181-r4173-1/javac-9+181-r4173-1.pom 403 Forbidden

### ISSUE THREAD

**Issue by zyyang-taosdata** [wgzhao/Addax#219]
**Describe the bug**
我clone了项目，并尝试编译。在执行mvn clean package时，出现截图中的错误。

![image](https://user-images.githubusercontent.com/69311263/124739868-d476dc00-df4c-11eb-8495-898cc4543872.png)

**Desktop (please complete the following information):**
 - OS: CentOS
 - JDK Version：1.8
 - Addax Version：master：f55779f5255ec1ab200a7e0e86d8c3a42490491a

**Comment by wgzhao** [comment]
感谢反馈
今天正在将项目更名
还没有完全迁移完
暂时请使用release版本的源代码

另外，从你的报错信息来看
似乎是访问maven仓库受限的原因


另，提交的错误信息尽可能使用文本而不是图片
谢谢

**Comment by zyyang-taosdata** [comment]
maven的settings.xml中配置alimaven的mirror，注释掉mirror后重新执行mvn clean package可以正常编译了
