### ISSUE TITLE
textfile reader 能否支持根据字段名指定列

### ISSUE THREAD

**Issue by calfzhou** [wgzhao/Addax#251]
目前的是这样：

> 读取字段列表，type指定源数据的类型，index指定当前列来自于文本第几列(以0开始)，value指定当前类型为常量，不从源头文件读取数据，而是根据value值自动生成对应的列。

但是源文件（一般是 csv 文件）中，第一行有可能是字段名，能够增加一些通过列名来指定字段的方式，这样对文件格式的容错会高很多，不用担心多了一列而导致数据列错位或者还得手动改动每一列的列号。

**Comment by wgzhao** [comment]
要实现这个的前提，其读取的文件的第一行必须是文件头，可以考虑增加这个特性
