### ISSUE TITLE
关于Addax的一个问题

### ISSUE THREAD

**Issue by jinyan2049** [wgzhao/Addax#266]
您好，所以Addax本身定位是离线数据采集，不支持实时采集录入，是吗？

**Comment by wgzhao** [comment]
是的，目前是定位离线数据采集。
实时采集要采取的方式和目前方式非常不同，特别要考虑到目标端是如何支持实时数据录入的。

另外，目前也有很优秀的开源软件支持实时数据采集，比如Spark， Flink等。
