### ISSUE TITLE
请教下项目里的数据库连接池参数在哪设置的？

### ISSUE THREAD

**Issue by weihebu** [wgzhao/Addax#269]
你好，请教下项目里的数据库连接池参数在哪设置的？

**Comment by weihebu** [comment]
url、username、password 这些我知道是从配置文件读的。但是像maxActive这个参数又是从哪里设置的呢，还是说没有设置用的都是默认值？

**Comment by weihebu** [comment]
目前这个项目用的是阿里巴巴的Druid连接池吗？

**Comment by wgzhao** [comment]
目前连接池等配置参数都是硬编码的，可以考虑做一个单独的配置项允许自定义。

连接池用的[Apache DBCP](https://commons.apache.org/proper/commons-dbcp/)

具体代码可以参考 `src/main/java/com/wgzhao/addax/rdbms/util/DBUtil.java#connect`

**Comment by weihebu** [comment]
谢谢。我还想问下datax原先用的是Druid连接池，这边出于什么原因换成DBCP呢？我现在遇到一个问题，就是Druid连接池会产生一条查询sql:
SELECT COUNT(*) FROM pg_class c LEFT JOIN pg_namespace n ON n.oid = c.relnamespace WHERE c.relkind = ANY ('{r,v,m}'::char[]) UNION SELECT COUNT(*) FROM pg_attribute a JOIN pg_class c on a.attrelid = c.oid JOIN pg_namespace n on c.relnamespace = n.oid JOIN pg_type tp on tp.typelem = a.atttypid WHERE a.attnum > 0 UNION SELECT COUNT(*) FROM information_schema.routines 
导致数据库卡顿，请问你这边是因为这个原因换的吗？

**Comment by weihebu** [comment]
我这边连接的源表数据库为postgresql。

**Comment by weihebu** [comment]
包括这条：SELECT n.nspname, c.relname, a.attname, tp.typname FROM pg_attribute a JOIN pg_class c on a.attrelid = c.oid JOIN pg_namespace n on c.relnamespace = n.oid JOIN pg_type tp on tp.oid = a.atttypid WHERE a.attnum > 0 ORDER BY nspname, relname

**Comment by wgzhao** [comment]
> 谢谢。我还想问下datax原先用的是Druid连接池，这边出于什么原因换成DBCP呢？我现在遇到一个问题，就是Druid连接池会产生一条查询sql:
> SELECT COUNT(_) FROM pg_class c LEFT JOIN pg_namespace n ON n.oid = c.relnamespace WHERE c.relkind = ANY ('{r,v,m}'::char[]) UNION SELECT COUNT(_) FROM pg_attribute a JOIN pg_class c on a.attrelid = c.oid JOIN pg_namespace n on c.relnamespace = n.oid JOIN pg_type tp on tp.typelem = a.atttypid WHERE a.attnum > 0 UNION SELECT COUNT(*) FROM information_schema.routines
> 导致数据库卡顿，请问你这边是因为这个原因换的吗？

`addax-rdbms` 引入 druid 并不是用来创建连接池的，仅仅是用到了里面的SQL语句校验工具类。

如果近期 `datax` 没有更新的话，其版本并不支持连接池方式。

**Comment by weihebu** [comment]
https://github.com/alibaba/druid/issues/3805
我是搜索到这个问题，我还以为是druid连接池产生的。sql语句一模一样，不是很懂什么情况下产生的。讲道理datax以及addax应该不会查这个才对。。。

**Comment by wgzhao** [comment]
如果方便，你可以给出完整的日志，这样可以定位大致是那个类的哪个方法在调用。
