### ISSUE TITLE
关于数据清洗

### ISSUE THREAD

**Issue by weihebu** [wgzhao/Addax#276]
你好，想问下Transform的配置，我这边想用groovy的方法方式进行数据清洗。但是我看手册里面并没有详细的说明，下方的参考也是四个函数。参考datax的那边又感到有些混乱，这边可以给个完整的示例吗？比如datax那边说 "code": "//groovy code//",  这里面groovy code 是替换成文档上面code=后面的代码吗？然后第一个code1示例那边，最后一行又加了dx_groovy(record);但是看后两个例子又是没有的。
附上两边链接：
https://addax.readthedocs.io/zh/latest/transformer.html
https://github.com/alibaba/DataX/blob/master/transformer/doc/transformer.md

**Comment by weihebu** [comment]
https://blog.csdn.net/MrZhangBaby/article/details/89636486
已查到相关配置，这边测试下。

**Comment by weihebu** [comment]
关于数据清洗原因为：从oracle导入数据到postgresql时，碰到了0x00错误。
附上相关链接：
https://www.cnblogs.com/wggj/p/8194313.html

**Comment by wgzhao** [comment]
> 关于数据清洗原因为：从oracle导入数据到postgresql时，碰到了0x00错误。
> 附上相关链接：
> https://www.cnblogs.com/wggj/p/8194313.html

能给出复现的表数据和测试 json文件吗？
或者告知如何生产可以出现 `0x00` 错误的数据

**Comment by wgzhao** [comment]
我已经复现了这个问题

**Comment by wgzhao** [comment]
如果你知道了是那个字段含有 `\0` ，那么可以不使用 `transformer` 这个插件，而直接在 `column` 里配置 `replace` 函数即可。

比如，假定是字段 `aa` 含有特定字符，我们需要读取时就替换掉，则可以这样配置：


```json
"column": [
     "replace(aa, chr(0),'')"
],
```

此方法在我本地环境测试成功，源是 `Oracle 11.2.0.1.0`， 目的是 `PosgreSQL 12.2`

**Comment by weihebu** [comment]
支持列裁剪，即列可以挑选部分列进行导出。
支持列换序，即列可以不按照表schema信息进行导出。
这两个功能哪里有说明吗？
另外替换的时可以的，但是替换应该会有帖子说的这个问题：
如果按照官方的推荐做法而直接对嫌疑字符串使用str.replaceAll('\u0000', '')，虽然避免了错误发生，之后的乱码却会存入数据库并最终显示在页面。
所以最好的方式还是截取，我这边原始数据被java读取后为：“其他\u0000ther”。

**Comment by wgzhao** [comment]
>支持列裁剪
意思是如果你的表有 `a`,`b`,`c` 三个字段，但是我在 `columns`里可以只填写 `a`,`c`

>支持列换序，即列可以不按照表schema信息进行导出
意思是如果你的表 `a`,`b`,`c` 三个字段，其顺序如此，但是我在 `columns`里可以填写 `a`,`c`,`b` 来更换 后面两个字段的顺序。

**Comment by weihebu** [comment]
附上我改的transformer，给有需要的人参考。
"transformer": [
          {
            "name": "dx_groovy",
            "parameter": {
              "code": "Column column = record.getColumn(42);String oriValue = column.asString();if(oriValue !=null && oriValue.length() != 0){ String newValue = oriValue.split('\u0000')[0];record.setColumn(42, new StringColumn(newValue)); };return record;",
              "extraPackage": []
            }
          }
        ]

**Comment by weihebu** [comment]
这两个明白了，"replace(aa, chr(0),'')" 在column里的这种写法，文档那里有说吗？

**Comment by wgzhao** [comment]
> 这两个明白了，"replace(aa, chr(0),'')" 在column里的这种写法，文档那里有说吗？是不是还支持其他的方法？

文档有说明的，在这里 https://addax.readthedocs.io/zh/latest/reader/rdbmsreader.html#column

**Comment by weihebu** [comment]
按照文档的意思，只要是这个表达式所在的数据库支持，就可以写对吧。

**Comment by wgzhao** [comment]
> 按照文档的意思，只要是这个表达式所在的数据库支持，就可以写对吧。

是的，实际上，你填写的 `column` 里的内容，最后变成了 `select` 后面的内容，因此只要数据库支持的表达式，均可在 `column` 配置

**Comment by weihebu** [comment]
好的，感谢。
