### ISSUE TITLE
kuduwriter写入数据丢失

### ISSUE THREAD

**Issue by niexiongchao** [wgzhao/Addax#294]
测试场景如下：
1.同一个集群内，将kudu表A的数据同步到kudu表B,使用kudureader进行读，kuduwriter进行写
数据量：A表200万条数据
测试结果如下：
1.报错：org.apache.kudu.client.NonRecoverableException: MANUAL_FLUSH is enabled but the buffer is too big
原因分析：bufferSize设置小于源表总数据量（200万），会存在该错误，查看源码，根本原因为缓存未刷新，导致数据量过大
2.bufferSize设置大于源表总数据量，未报错，作业同步提示完成，但数据未同步到B表，原因同样是未flush
3.batchSize未生效，查看源码，并未使用该参数

解决方案：
在KuduWriterTask类修改如下：

    public void startWriter(RecordReceiver lineReceiver, TaskPluginCollector taskPluginCollector)
    {
        LOG.info("kuduwriter begin to write!");
        Record record;
        int commit=0;
        List<Configuration> columns = configuration.getListConfiguration(KuduKey.COLUMN);
        List<String> columnNames = KuduHelper.getColumnNames(columns);
        while ((record = lineReceiver.getFromReader()) != null) {
            if (record.getColumnNumber() != columns.size()) {
                throw AddaxException.asAddaxException(KuduWriterErrorCode.PARAMETER_NUM_ERROR,
                        " number of record fields:" + record.getColumnNumber()
                                + " number of configuration fields:" + columns.size());
            }
            Upsert upsert = table.newUpsert();
            Insert insert = table.newInsert();
            PartialRow row;
            if (isUpsert) {
                //覆盖更新
                row = upsert.getRow();
            }
            else {
                //增量更新
                row = insert.getRow();
            }
            for (int i = 0; i < record.getColumnNumber(); i++) {
                Column column = record.getColumn(i);
                String name = columnNames.get(i);
                if (column.getRawData() == null) {
                    row.setNull(name);
                    continue;
                }
                Type type = Type.getTypeForName(columns.get(i).getString(KuduKey.TYPE));
                switch (type) {
                    case INT8:
                    case INT16:
                    case INT32:
                    case INT64:
                        row.addInt(name, Integer.parseInt(column.asString()));
                        break;
                    case FLOAT:
                    case DOUBLE:
                        row.addDouble(name, column.asDouble());
                        break;
                    case STRING:
                        row.addString(name, column.asString());
                        break;
                    case BOOL:
                        row.addBoolean(name, column.asBoolean());
                        break;
                    case BINARY:
                        row.addBinary(name, column.asBytes());
                        break;
                    case DECIMAL:
                        row.addDecimal(name, new BigDecimal(column.asString()));
                        break;
                    case UNIXTIME_MICROS:
                        row.addTimestamp(name, new Timestamp(column.asLong()));
                        break;
                    case DATE:
                        row.addDate(name,
                                (Date) new java.util.Date(column.asDate().getTime()));
                        break;
                    default:
                        throw AddaxException.asAddaxException(
                                KuduWriterErrorCode.ILLEGAL_VALUE, "The data type " + type + "is unsupported"
                        );
                }

            } // end a row
            try {
                if (isUpsert) {
                    session.apply(upsert);
                }
                else {
                    session.apply(insert);
                }
            //刷新缓存
                commit++;
                if (commit == batchSize ) {
                    session.flush();
                    commit = 0;
                }

            }
            catch (Exception e) {
                LOG.error("Record Write Failure!", e);
                if (isSkipFail) {
                    LOG.warn("Since you have configured \"skipFail\" to be true, this record will be skipped !");
                    taskPluginCollector.collectDirtyRecord(record, e.getMessage());
                }
                else {
                    throw AddaxException.asAddaxException(KuduWriterErrorCode.PUT_KUDU_ERROR, e.getMessage());
                }
            }
        }

        try {
          //提交最后一次数据
            session.flush();
        } catch (Exception e) {
            LOG.error("Record Write Failure!", e);
            if (isSkipFail) {
                LOG.warn("Since you have configured \"skipFail\" to be true, this record will be skipped !");
                taskPluginCollector.collectDirtyRecord(record, e.getMessage());
            }
            else {
                throw AddaxException.asAddaxException(KuduWriterErrorCode.PUT_KUDU_ERROR, e.getMessage());
            }
        }

    }

**Comment by wgzhao** [comment]
非常感谢反馈并给出解决方案
我加入到代码中
