### ISSUE TITLE
kudureader不支持部分列同步、不支持条件查询

### ISSUE THREAD

**Issue by niexiongchao** [wgzhao/Addax#295]
1.只能同步所有列
2.不支持条件查询，则只能全量同步数据，无法增量同步
希望作者能过优化，才能更好推广

**Comment by wgzhao** [comment]
好的
kudu 我还需要好好研究，之前用得不多。

**Comment by wgzhao** [comment]
Repeated with #252

**Comment by wgzhao** [comment]
已经支持定制列，配置 `parameter` 下的 `column` 即可，类似

```json
{
"column":["user_id","user_name"]
}
```

**Comment by wgzhao** [comment]
Fixed with #297 ,  #298
