### ISSUE TITLE
mysql里的geometry类型，转到pgsql里的geometry类型

### ISSUE THREAD

**Issue by zhbdesign** [wgzhao/Addax#300]
mysql里的geometry类型，转到pgsql里的geometry类型，可以支持一下这个类型吗

**Comment by wgzhao** [comment]
你可以测试看，如果问题的话，我尝试修复

**Comment by zhbdesign** [comment]
> 你可以测试看，如果问题的话，我尝试修复

回滚此次写入, 采用每次写入一行方式提交. 因为: Batch entry 0 INSERT INTO cfo_data_9rd35jat (fd4vljv3bw) VALUES('       
?p=R\@?? ?r?8@'::geometry) was aborted: ERROR: invalid byte sequence for encoding "UTF8": 0x00  Call getNextException to see other errors in the batch.
是不是要在reader里支持geometry，或者字段默认添加ST_ASTEXT函数

**Comment by wgzhao** [comment]
好的，我找时间测试下

**Comment by wgzhao** [comment]
@zhbdesign 看了两者对 Geometry 的处理，差异太大了。
妥当的办法是读取是转为文本（比如字符串，json串等），写入时使用采取文本到 Geometry 的函数进行转换后写入。

**Comment by zhbdesign** [comment]
> @zhbdesign 看了两者对 Geometry 的处理，差异太大了。
> 妥当的办法是读取是转为文本（比如字符串，json串等），写入时使用采取文本到 Geometry 的函数进行转换后写入。

读取这一块你那边可以需改为自动转为字符串吗

**Comment by zhbdesign** [comment]
> @zhbdesign 看了两者对 Geometry 的处理，差异太大了。
> 妥当的办法是读取是转为文本（比如字符串，json串等），写入时使用采取文本到 Geometry 的函数进行转换后写入。

ST_ASTEXT这个函数添加在哪个地方，找了下，感觉改的地方还挺多

**Comment by wgzhao** [comment]
修改你的 `column` 配置，对 geometry 字段增加 `ST_ASTEXT` 函数，不过我看 MySQL 使用 `ST_ASTEXT` 读取出来的数据还是类似 `LINESTRING(2 1,6 6)` 这样的值，这种恐怕其他数据都不支持

**Comment by zhbdesign** [comment]
> 修改你的 `column` 配置，对 geometry 字段增加 `ST_ASTEXT` 函数，不过我看 MySQL 使用 `ST_ASTEXT` 读取出来的数据还是类似 `LINESTRING(2 1,6 6)` 这样的值，这种恐怕其他数据都不支持

我现在用的是*，不知道在哪里加上这个函数，自动转，我想这样测试一下

**Comment by wgzhao** [comment]
请参考这个文档说明 https://addax.readthedocs.io/zh/latest/reader/rdbmsreader.html#column

**Comment by zhbdesign** [comment]
> 请参考这个文档说明 https://addax.readthedocs.io/zh/latest/reader/rdbmsreader.html#column

"column":[“*”]，dataX会自动转成select id 这样，我怎么在代码里修改，给字段加上一个函数，我想这样尝试一下

**Comment by wgzhao** [comment]
你需要明确的把每个字段都写出来，类似这样

```json
{
  "column":["col1", "col2", "ST_ASTEXT(col3)"]
}
```

**Comment by zhbdesign** [comment]
> 你需要明确的把每个字段都写出来，类似这样
> 
> ```json
> {
>   "column":["col1", "col2", "ST_ASTEXT(col3)"]
> }
> ```

![image](https://user-images.githubusercontent.com/50901800/130207875-e8c00c70-6148-4223-9157-9944633eee88.png)
可以ji夹在这里吗，主要是想用*，方便一些

**Comment by wgzhao** [comment]
你可以单独按照你的需求定制这个模块，然后替换默认的模块即可。
但作为通用插件，硬编码一则不符合规范，二则如果其他使用者并不想调用该函数，该如何处理呢？
