### ISSUE TITLE
elasticsearch writer 支持版本问题

### ISSUE THREAD

**Issue by grunt1024** [wgzhao/Addax#313]
elasticsearch writer 支持到ES哪个版本？支持父子文档导入吗？

**Comment by grunt1024** [comment]
文档说明中的示例，是简单格式的，能够导入，已经经过测试。

但使用Addax 4.0.2 版本，无法导入ES父子文档类型数据（父子文档里面需要设置routing，join类型字段等），首先想向作者求证：当前版本是否确实不能支持父子文档类型？如果可以支持，是否可以给一个样例？

如果当前确实不支持，是否有计划在后续版本中考虑支持？如果短时间内不能支持的话，我想基于当前版本拓展elasticsearch writer模块。

**Comment by wgzhao** [comment]
当前插件目前支持的文档类型以及数据类型在[文档说明](https://addax.readthedocs.io/zh/latest/writer/elasticsearchwriter.html) 里已经全部列出。
当前还不支持父子文档类型数据。
欢迎增加新功能并提交PR

**Comment by grunt1024** [comment]
好的，多谢。
