### ISSUE TITLE
如何本地调试？

### ISSUE THREAD

**Issue by grunt1024** [wgzhao/Addax#336]
想要在本地打断点调试，请问如何操作？先表示感谢。

**Comment by wgzhao** [comment]
这两天我增加一个如何调试的文档，大致分成两种（已Intellij IDEA 开发工具为例）
## 本地方式：
 在项目配置里，在 "Run/Debug configurations" 增加一个 "Application", 配置相关信息，然后打断点调试。
## 远程调试：
 在远程服务器上执行 `bin/addax.sh -d xxx.json` 文件，默认调试端口是 `9999`
在项目配置里，在 "Run/Debug configurations" ，增加一个 "Remote JVM Debug" 配置项，按照要求填写主机名和端口，然后开始调试（提前打好断点）

**Comment by wgzhao** [comment]
这两天我增加一个如何调试的文档，大致分成两种（已Intellij IDEA 开发工具为例）
## 本地方式：
 在项目配置里，在 "Run/Debug configurations" 增加一个 "Application", 配置相关信息，然后打断点调试。
## 远程调试：
 在远程服务器上执行 `bin/addax.sh -d xxx.json` 文件，默认调试端口是 `9999`
在项目配置里，在 "Run/Debug configurations" ，增加一个 "Remote JVM Debug" 配置项，按照要求填写主机名和端口，然后开始调试（提前打好断点）

**Comment by grunt1024** [comment]
> 这两天我增加一个如何调试的文档，大致分成两种（已Intellij IDEA 开发工具为例）
> 
> ## 本地方式：
> 在项目配置里，在 "Run/Debug configurations" 增加一个 "Application", 配置相关信息，然后打断点调试。
> 
> ## 远程调试：
> 在远程服务器上执行 `bin/addax.sh -d xxx.json` 文件，默认调试端口是 `9999`
> 在项目配置里，在 "Run/Debug configurations" ，增加一个 "Remote JVM Debug" 配置项，按照要求填写主机名和端口，然后开始调试（提前打好断点）

—————————————————————————————————————————————————————

针对本地方式调试方式疑问：
    public static void main(String[] args)
    {
        System.out.println("\n  ___      _     _            \n" +
                " / _ \\    | |   | |           \n" +
                "/ /_\\ \\ __| | __| | __ ___  __\n" +
                "|  _  |/ _` |/ _` |/ _` \\ \\/ /\n" +
                "| | | | (_| | (_| | (_| |>  < \n" +
                "\\_| |_/\\__,_|\\__,_|\\__,_/_/\\_\\\n");
        System.out.println(":: Addax version ::    (v" + Engine.getVersion() + ")\n");
        int exitCode = 0;
        if (args.length < 2) {
            LOG.error("need a job file");
            System.exit(1);
        }


如果手动设置配置信息，是配置到 args 里面吗？具体格式是什么，里面都需要设置哪些信息，可以在项目源码中找到吗？

**Comment by wgzhao** [comment]
请参考 [如何调试](https://addax.readthedocs.io/zh/latest/debug.html) 一文

**Comment by wgzhao** [comment]
dc3973d has added how to debug guide

**Comment by grunt1024** [comment]
1，我下载了源码，切换到了 4.0.2 分支。pom 文件中删除掉了用不上的 module，执行 mvn  clean package -pl  '!:addax-docs'

[INFO] Reactor Summary for addax-all 4.0.2:
[INFO] 
[INFO] addax-all .......................................... SUCCESS [  1.040 s]
[INFO] addax-common ....................................... SUCCESS [  4.700 s]
[INFO] addax-transformer .................................. SUCCESS [  1.070 s]
[INFO] addax-core ......................................... SUCCESS [  3.486 s]
[INFO] addax-rdbms ........................................ SUCCESS [  2.057 s]
[INFO] addax-storage ...................................... SUCCESS [  1.513 s]
[INFO] mysql-reader ....................................... SUCCESS [  1.800 s]
[INFO] oracle-reader ...................................... SUCCESS [  1.159 s]
[INFO] stream-reader ...................................... SUCCESS [  1.219 s]
[INFO] elasticsearch-writer ............................... SUCCESS [  1.614 s]
[INFO] mysql-writer ....................................... SUCCESS [  1.203 s]
[INFO] oracle-writer ...................................... SUCCESS [  1.156 s]
[INFO] stream-writer ...................................... SUCCESS [  1.180 s]

按照本地调试文档配置，本地 debug，结果报 hdfsreader/plugin.json 不存在。hdfsreader 模块已经注释掉了，为什么还会找hdfsreader/plugin.json文件。是哪里操作的有问题吗？

Connected to the target VM, address: '127.0.0.1:50438', transport: 'socket'

  ___      _     _            
 / _ \    | |   | |           
/ /_\ \ __| | __| | __ ___  __
|  _  |/ _` |/ _` |/ _` \ \/ /
| | | | (_| | (_| | (_| |>  < 
\_| |_/\__,_|\__,_|\__,_/_/\_\

:: Addax version ::    (v4.0.2)

23:28:51.175 [main] WARN com.wgzhao.addax.core.util.ConfigParser - 插件[streamreader,streamwriter]加载失败，1s后重试... Exception:Code:[Common-00], Describe:[您提供的配置文件存在错误信息，请检查您的作业配置 .] - 配置信息错误，您提供的配置文件[/Users/hua/Documents/Addax/addax/plugin/reader/hdfsreader/plugin.json]不存在. 请检查您的配置文件. 
23:28:52.184 [main] ERROR com.wgzhao.addax.core.Engine - Code:[Common-00], Describe:[您提供的配置文件存在错误信息，请检查您的作业配置 .] - Code:[Common-00], Describe:[您提供的配置文件存在错误信息，请检查您的作业配置 .] - 配置信息错误，您提供的配置文件[/Users/hua/Documents/Addax/addax/plugin/reader/hdfsreader/plugin.json]不存在. 请检查您的配置文件.
Disconnected from the target VM, address: '127.0.0.1:50438', transport: 'socket'

**Comment by wgzhao** [comment]
是不是有断点打在了 hdfsreader 插件上？

**Comment by grunt1024** [comment]
> 是不是有断点打在了 hdfsreader 插件上？

没有断点在 hdfsreader。放开断点之后也是报这个错误信息。

**Comment by wgzhao** [comment]
目录是 `/Users/hua/Documents/Addax/addax` 二进制部署目录吗还是源代码目录？如果是源代码目录，还需要一个部署目录。
另外，尝试把项目根目录下的 `package.xml` 里其他模块的相关内容也一并删除再试试。

**Comment by grunt1024** [comment]
> 目录是 `/Users/hua/Documents/Addax/addax` 二进制部署目录吗还是源代码目录？如果是源代码目录，还需要一个部署目录。
> 另外，尝试把项目根目录下的 `package.xml` 里其他模块的相关内容也一并删除再试试。

`/Users/hua/Documents/Addax/addax` 是源码目录。
  还需要一个部署目录是指什么？里面放置什么内容？
——————————————————————————————

另外，按照我一开始的猜想，直接启动程序 main 入口，设置好json 配置文件路径，不就应该可以直接 debug 了吗，为什么还需要源码和二进制包一起配合调试？

**Comment by grunt1024** [comment]
> 目录是 `/Users/hua/Documents/Addax/addax` 二进制部署目录吗还是源代码目录？如果是源代码目录，还需要一个部署目录。
> 另外，尝试把项目根目录下的 `package.xml` 里其他模块的相关内容也一并删除再试试。

在 run/debug configuration 里面把 working 设置成编译后的 target 路径可以调试了。
