### ISSUE TITLE
阿里云下载链接失效

### ISSUE THREAD

**Issue by milton4code** [wgzhao/Addax#337]
![image](https://user-images.githubusercontent.com/13265817/131978318-f56e6171-354d-4290-8ff2-af74f4a108cf.png)

文件违规，根据相关法律法规要求，该文件已禁止访问

**Comment by wgzhao** [comment]
呃，那就从github上我上传的附件里下载吧

**Comment by wgzhao** [comment]
不再上传到公有云盘，直接附加到github上
