### ISSUE TITLE
addax能支持excel数据源么？

### ISSUE THREAD

**Issue by milton4code** [wgzhao/Addax#339]
希望addax能支持excel数据源

**Comment by cxin-william** [comment]
excel自己学下pandas就好了

**Comment by wgzhao** [comment]
感谢反馈
感谢 @cxin-william 的回答

目前 Addax 还不支持 Excel 作为数据源的读取，不过如果是针对简单，条件受限下的Excel文件读取，比如只读取Excel第一个sheet，所有的字段类型为String，或者需要单独配置 `column` 来指定每个字段的类型，不能有合并单元格的情况等。

**Comment by wgzhao** [comment]
已经初步支持 Excel 文件读取，相关配置以及注意事项，请[参阅文档](https://addax.readthedocs.io/zh/latest/reader/excelreader.html)

**Comment by wgzhao** [comment]
[plugins] Add Excel Writer plugin (#350)
