### ISSUE TITLE
请问一下，此工具是否支持SQL语句？

### ISSUE THREAD

**Issue by ewsq** [wgzhao/Addax#340]
了解了一下这个工具，理解如下：

1、此工具是一种数据源表向另一种数据源表传输数据，并且可以根据表抽取剪载字段或转换字段数据。

疑问：
1、一个job仅支持一个表？没有看到一个job多表操作的示例
2、对于job仅支持表？是否支持SQL语句？也就是可能我的job源是一个多表查询的结果，然后输出到一个目标中的一个表中。如果没有，是否考虑支持？
3、从现在的理解，此工具仅是一个数据转输工具，是否考虑了同步？即数据的实时增量同步？或者现在支持的话是否有相应示例或文档？

能否帮释疑一下？谢谢！

**Comment by grunt1024** [comment]
工具定位：离线异构数据源同步工具。
1，数据抽取可支持连表；
2，同上；
3，不支持实时同步。

**Comment by grunt1024** [comment]
> 了解了一下这个工具，理解如下：
> 
> 1、此工具是一种数据源表向另一种数据源表传输数据，并且可以根据表抽取剪载字段或转换字段数据。
> 
> 疑问：
> 1、一个job仅支持一个表？没有看到一个job多表操作的示例
> 2、对于job仅支持表？是否支持SQL语句？也就是可能我的job源是一个多表查询的结果，然后输出到一个目标中的一个表中。如果没有，是否考虑支持？
> 3、从现在的理解，此工具仅是一个数据转输工具，是否考虑了同步？即数据的实时增量同步？或者现在支持的话是否有相应示例或文档？
> 
> 能否帮释疑一下？谢谢！

如果需要做实时增量同步，可以考虑 CDC ：change data capture；比如canal 框架

**Comment by wgzhao** [comment]
感谢 @grunt1024 的回复，我这里补充一下
> 1、一个job仅支持一个表？没有看到一个job多表操作的示例

一个job，有两种方式获取数据的方式
1. 直接指定表名，通过 `table` 配置项，此时仅支持单表
2. 指定 `querySql` 配置，写上你的SQL语句，比如 `select a.*,b.* from a left join b on a.id = b.id` ，此时程序会直接获取该SQL的输出结果，然后传递给 `writer` 插件

所以，是支持多表的操作的，当然你可以把SQL语句写入到一个视图中，然后 `table` 指定视图来达到同样的效果。

> 3. 即数据的实时增量同步

Addax 的定位是离线的 ETL 工具，因此对于实时增量并不支持，半离线的增量同步倒是可以通过一定的配置来达到，但这不是 Addax 的目标。如果需要适时同步，您可能需要另外的实时采集工具，比如 @grunt1024 提到的 [canal](https://github.com/alibaba/canal) 来实时采集 MySQL的数据，[Oracle OGG](https://www.oracle.com/cn/middleware/technologies/goldengate/overview.html) 实时采集Oracle的数据等。

**Comment by ewsq** [comment]
@wgzhao @grunt1024 感谢两位的耐心细致回复！

table，querySQL 可用其一？大致看了一下源码，好像两个有获得了，后来事情打扰了还没看完，是做了二选一处理？

**Comment by wgzhao** [comment]
请参考 这个文档， https://addax.readthedocs.io/zh/latest/reader/rdbmsreader.html

**Comment by ewsq** [comment]
@wgzhao @grunt1024 感谢两位的耐心细致回复！

table，querySQL 可用其一？大致看了一下源码，好像两个有获得了，后来事情打扰了还没看完，是做了二选一处理？

> 请参考 这个文档， https://addax.readthedocs.io/zh/latest/reader/rdbmsreader.html

看了文档，table是必选的，querySQL是非必选的，那么，是优先querySQL？

**Comment by wgzhao** [comment]
两者都配置的话
则忽略 table 配置

**Comment by ewsq** [comment]
> 单一配置时，不存在谁优先的问题
> 
> 仅在两者都配置的话
> 则选择 querySql 配置而忽略 table 配置

明白了，谢谢您！
