### ISSUE TITLE
希望增加opengauss数据库的同步组件

### ISSUE THREAD

**Issue by cmdares** [wgzhao/Addax#344]
近期项目有要求要用国货，希望能够支持该数据库。观察数据库社区近期的发展情况，未来opengauss定将成爆发式增长的态势，希望能够早日支持该数据库同步的能力。感谢。

**Comment by wgzhao** [comment]
感谢反馈。
按照[官方文档](https://opengauss.org/zh/docs/2.0.1/docs/Developerguide/JDBC包-驱动类和环境类.html) 的说法：

>驱动包与PostgreSQL保持兼容，其中类名、类结构与PostgreSQL驱动完全一致，曾经运行于PostgreSQL的应用程序可以直接移植到当前系统使用。

因此可以直接使用 `postgresqlreader`, `postgresqlwriter` 插件进行读取和写入。

**Comment by cmdares** [comment]
感谢您的关注！
