### ISSUE TITLE
几个疑问

### ISSUE THREAD

**Issue by wushanru** [wgzhao/Addax#351]
1、Addax有B/S图形化的管理界面吗？
2、有和datax进行比较的稳定性及性能测试报告吗？
3、有打算进行持续维护吗？

**Comment by wgzhao** [comment]
1. Addax 本身仅限于ETL工具自身，不会有B/S工具，社区有一些不错的工具可以使用
2. 和 datax 没有进行比较，项目就是从 datax 而来，核心代码暂时没有太大变动，Addax 一直在我司的生成环境使用，涉及到Oracle，MySQL， PostgreSQL，SQL Server， Impala， Hive， DBF等数据源，每天运行几个个任务，压缩后的数据量几百G，目前一切运行正常。
3. 没有特别的情况，会一直维护下去，这套工具也是目前我司数据采集的唯一工具，所以稳定性和功能性都非常重要
