### ISSUE TITLE
任务分片问题

### ISSUE THREAD

**Issue by grunt1024** [wgzhao/Addax#359]
在抽取oracle数据时候，如果手动设置querySql，那么就不能配置splitPk，就会使用单线程抽取数据。是否有解决办法？

**Comment by wgzhao** [comment]
自定义 SQL 语句后，可能会出现 splitPK 无法使用的情况，比如 splitPK，并不在 select 字段里，又或者 SQL 里可能是多表查询，如果把 splitPK 加入到 自定义的 SQL 中也比较麻烦。还有可能是 splitPK 可能在多表中都存在，如果决定应该在那张表中应用 splitPK，这些都会存在很大的问题。

所以暂时不会考虑。

**Comment by wgzhao** [comment]
另外一种情况，如果把 SQL 创建为一个视图， 然后指定 splitPK，这种情况我还没有测试过，你可以测试看看是否可行。

**Comment by wgzhao** [comment]
这种是可以的，不过注意 SQL 条数的限制，参考 #342
