### ISSUE TITLE
hdfswriter的writeMode下nonConflict判断错误

### ISSUE THREAD

**Issue by nmgliangwei** [wgzhao/Addax#361]
hdfswriter 代码中对writeMode这块处理有问题.
https://github.com/wgzhao/Addax/blob/95ed79c037985244e08662c93b599b0e9fa346f4/plugin/writer/hdfswriter/src/main/java/com/wgzhao/addax/plugin/writer/hdfswriter/HdfsWriter.java#L124
这块做了小写转换
而在Constant中是大写的
public static final Set<String> SUPPORTED_WRITE_MODE = new HashSet<>(Arrays.asList("append", "nonConflict", "overwrite", "truncate"));

**Comment by wgzhao** [comment]
感谢反馈
nonconflict 这个item我一直觉得没有很好表达其含义
想换换个变量名

**Comment by nmgliangwei** [comment]
因为我的很多任务都是datax的,用到了这个值,所以我暂时将Constant中改为小写了.目前测试使用没问题. 
建议保留方便 datax 的用户直接切过来,任务无需修改即可使用.
后面的任务可以使用overwrite 基本上就不需要nonconflict了.

**Comment by wgzhao** [comment]
是基于这个考虑，所有参数基本没有变动
