### ISSUE TITLE
mysql-reader不支持5.6

### ISSUE THREAD

**Issue by nmgliangwei** [wgzhao/Addax#365]
addax版本:4.0.3
mysql-reader不支持5.6
在我们的场景中需要同时支持 5.6,5.7,8.0 目前测试 8.0 没问题,但是 5.6 有问题.
5.6报错信息如下:
java.sql.SQLException: Cannot create PoolableConnectionFactory (CLIENT_PLUGIN_AUTH is required).

**Comment by wgzhao** [comment]
是的，目前自带的驱动不支持 5.6，但是可以指定驱动名来支持低版本，具体配置请参考[MySQL Reader Driver章节](https://wgzhao.github.io/Addax/reader/mysqlreader/#driver)

**Comment by nmgliangwei** [comment]
怎么能既支持 8.0 也支持 5.6 呢

**Comment by wgzhao** [comment]
两个不兼容
一个驱动肯定不能解决问题
你可以尝试把driver配置为一个变量
然后命令行通过传递参数来指定驱动名和驱动路径

**Comment by nmgliangwei** [comment]
我目前的做法是采用 mysql-connector-java-5.1.49 的驱动,类名称com.mysql.jdbc.Driver, 5.6 和 8.0 都可以读数据了. 但是担心后面会有兼容性问题.
驱动路径在 json 里可以指定吗.没找到可以指定的参数.
不知道能否做成:
1. json 文件可以指定使用的驱动名称mysql-connector-java-xxx.jar 和驱动类名称
2. 将mysql-connector-java-xxx.jar  不同版本的都放到 lib 下, 每次根据 json 指定的去加载驱动和使用指定的类名称

**Comment by wgzhao** [comment]
>将mysql-connector-java-xxx.jar 不同版本的都放到 lib 下, 每次根据 json 指定的去加载驱动和使用指定的类名称

这个会导致类名冲突的，你估计要自己写个简单的脚本，根据不同的 MySQL 版本，来替换不同的 JDBC 驱动包
