### ISSUE TITLE
如何打包成tar.gz

### ISSUE THREAD

**Issue by milton4code** [wgzhao/Addax#367]
将addax进行改造后如何打包成tar.gz ?和作者提供的tar.gz一样的那种,有shared包,并且依赖jar可以自动生成链接?

![image](https://user-images.githubusercontent.com/13265817/134612465-a85add45-908b-48fc-92df-b5dd5e5e189d.png)

**Comment by wgzhao** [comment]
大致步骤如下：

```shell
mvn clean package
mvn package assembly:single
bash shrink_package.sh
```
