### ISSUE TITLE
oracle->oracle存在时间精度丢失问题

### ISSUE THREAD

**Issue by zhbdesign** [wgzhao/Addax#368]
oracle版本为19.11
在做oracle到oracle抄写时候，时间类型为timestamp，例如时间为2021-09-25 10:50:00 123456抄写到目标端oracle变成2021-09-25 10:50:00 123000，丢失后面3位精度。

**Comment by wgzhao** [comment]
默认的时间格式为 `yyyy-MM-dd HH:mm:ss`，尝试配置 `dateFormat` 为正确的时间格式，再测试看看

**Comment by zhbdesign** [comment]
试了下不行，估计要优化代码处理

**Comment by wgzhao** [comment]
等于要支持 `timestamp(p)` 这种格式，这个改动估计比较大，不仅仅是 Oracle 这一个插件，而是全局上的
我看看怎么改比较好

**Comment by wgzhao** [comment]
新增了一个 `timestamp` 类型，目前本地测试修复了精读丢失了问题，这几天会合并到主干分支，下个发行版本修复该问题。

**Comment by zhbdesign** [comment]
> 新增了一个 `timestamp` 类型，目前本地测试修复了精读丢失了问题，这几天会合并到主干分支，下个发行版本修复该问题。

代码没提上去吗，我先自己打包下

**Comment by wgzhao** [comment]
已经提交，暂未合并到master分支。
只需要重新编译 `common`, `addax-rdbms` 两个模块，并替换对应的jar包即可。
如果你测试完毕，麻烦给我一个反馈
