### ISSUE TITLE
oraclereader to oraclewriter  报用户名密码错误

### ISSUE THREAD

**Issue by grunt1024** [wgzhao/Addax#370]
版本：  4.0.2
问题描述：A和B两个都是oracle数据源，当用B oraclereader，streamwriter输出正常；

当把A当做oraclereader，B作为 oraclewriter，报用户名密码错误，可以保证用户名和密码没有问题。

<img width="805" alt="微信截图_20210927165855" src="https://user-images.githubusercontent.com/8295556/134877685-9af4854e-e5c6-4afe-b2d3-802165bc3f2e.png">

**Comment by wgzhao** [comment]
尽可能不要贴截图
而是粘贴输出文本
从报错的信息来看
是账号密码的问题
运行节点有权限吗
如果节点有客户端
直接用客户端连接
看看是否有该错误

**Comment by grunt1024** [comment]
是 oraclewriter格式写错了，写成了    "jdbcUrl": ["jdbc:oracle:thin:@//172.16.212.100:1521/orcl"]，
改为   "jdbcUrl": "jdbc:oracle:thin:@//172.16.212.100:1521/orcl"  就正常了。
