### ISSUE TITLE
querysql不支持换行

### ISSUE THREAD

**Issue by zhbdesign** [wgzhao/Addax#386]
### What happened?

querysql不支持换行

### Version

4.0.4 (Default)

### Java JDK Version

Oracle JDK 1.8.0

**Comment by wgzhao** [comment]
能否详细说明以及运行日志，是 json 本身就不支持换行还是 json 格式没有问题，程序解析报错了？

**Comment by zhbdesign** [comment]
> 能否详细说明以及运行日志，是 json 本身就不支持换行还是 json 格式没有问题，程序""

> 能否详细说明以及运行日志，是 json 本身就不支持换行还是 json 格式没有问题，程序解析报错了？

"querysql":"select a,b,
c from table"，这样就会报错

**Comment by wgzhao** [comment]
本地测试并没有报错，请贴出完整的任务输出日志
