### ISSUE TITLE
你好，有社区或者交流群吗

### ISSUE THREAD

**Issue by wgzhao** [wgzhao/Addax#387]
你好，有社区或者交流群吗？使用addax插件时遇到一些问题，mysql的读没有问题，可是oracle和execl都一直报错： Code:[Framework-03], Description:[Addax 引擎配置错误，该问题通常是由于Addax 安装错误引起，请联系您的运维解决 .].。我从4.0.2试到4.0.5都不行。

_Originally posted by @llyxd in https://github.com/wgzhao/Addax/issues/360#issuecomment-940709463_

**Comment by wgzhao** [comment]
目前没有创建其他社区或者交流群

1. github本身就是社区，可以通过创建 issue 或者在 disussions 上讨论相关问题
2. 交流群往往变成了广告群，其技术交流的质量并不高，而且不容易沉底内容以及外部搜索。

您遇到报错，可以把运行的完整日志贴出来（不要截图）

**Comment by llyxd** [comment]
> 现在没有其他社区或者交流群
> 
> 1. github讨论就是社区，可以通过创建问题或者在讨论上相关问题
> 2. 交流群往往外部了广告群，其技术交流的质量并不高，也不容易沉底内容以及搜索。
> 
> 你遇到了报错，可以把运行的完整日志贴出来（不要截图）

好的好的。谢谢！我把日志贴在评论区了。

**Comment by llyxd** [comment]
excelreader里面的path路径的指定规则是什么。我看文档上没细说，不知道 是不是路径问题。我把excel文件放在了tmp目录下，工具包也是在tmp目录下。
{
  "job": {
    "setting": {
      "speed": {
        "channel": 1,
        "bytes": -1
      }
    },
    "content": [
      {
        "reader": {
          "name": "excelreader",
          "parameter": {
            "path": ["/tmp/"],--这里尝试过/tmp       /tmp/excelreader.json
            "header": true,
            "skipRows": 0
          }
        },
        "writer": {
          "parameter": {
            "print": true
          },
          "name": "streamwriter"
        }
      }
    ]
  }
}
