### ISSUE TITLE
能否把一些功能rest服务化，便于集成和远端调用

### ISSUE THREAD

**Issue by cmdares** [wgzhao/Addax#389]
将job执行，查看结果日志等操作功能服务化，能够动态传参，发布rest服务，便于外部系统整合，集成。
感谢！

**Comment by wgzhao** [comment]
这个原本是打算做到另外一个管理工具里的，但限于时间和能力关系，有了初步代码，但还没有到可以发布的程度

**Comment by wgzhao** [comment]
大致是想用 springboot 做一个简单的管理工具，用于管理job文件，日志。有简单的任务执行功能（直接调用addax），但不具备调度功能。
提供日志查看以及job文件导出等接口，便于和调度集成

**Comment by a19920714liou** [comment]
我看addax中是增加了hook去将最后结果发到接口中，哪如果我是TaskGroupContainer的start中增加hook是不是就可以有一个实时进度？
