### ISSUE TITLE
[Bug]: oracle写入bug

### ISSUE THREAD

**Issue by zwq15210498715** [wgzhao/Addax#414]
### Contact Details（联系人）

1340573572@qq.com

### What happened?

 对于oracle的批量写入
1、发生的bug：oracle写入的时候，CommonRdbmsWriter$Task的fillPreparedStatement方法resultSetMetaData.getColumnType获取字段，报索引异常
2、bug原因：DBUtil的getColumnMetaData方法，获取的ResultSetMetaData对象，Statement关闭的时候，oracle的ResultSetMetaData对象内容会为空。
3、解决方法：还是考虑使用变量，存储ResultSetMetaData对象的结果，为减少改动，可考虑使用一个和ResultSetMetaData获取数据格式类似的变量。

### Version

4.0.4 (Default)

### OS Type

Windows

### Java JDK Version

Oracle JDK 1.8.0

**Comment by wgzhao** [comment]
The new release 4.0.6 has fixed it.
