### ISSUE TITLE
[Bug]: 在传入复杂的条件参数时，会无法运行

### ISSUE THREAD

**Issue by ldeng76** [wgzhao/Addax#445]
### What happened?

背景：希望不写死Job配置文件，而让它可配置化，如 where 条件 可配置。

步骤：
1. 在 Job配置文件中加入： "where":"${mywhere}" 
2. 运行前设置好变量 ： mywhere="globalid=1 or globalid=2"
3. 执行时传入变量 :   -p"-Dusername=${dbUser} -Durl=${dbUrl} -Dpassword=${dbPwd} -Dmywhere='${mywhere}' "

结果：任务无法执行，报错信息：
Error: Could not find or load main class and

尝试出的一种解决办法：
将 addax.sh 的最后一行 由  ${cmd}  改为 eval ${cmd}   就可以了。原理不懂，但能解决问题。

注：使用的版本是 4.0.7 

### Version

4.0.4 (Default)

### OS Type

Linux (Default)

### Java JDK Version

Oracle JDK 1.8.0

**Comment by wgzhao** [comment]
改成 `bash -c ${cmd}` 应该更合适

**Comment by Tandoy** [comment]
@wgzhao 
Hello, have you considered adding this modification to the master branch? Thank you.

**Comment by wgzhao** [comment]
The commit c73dd08332324a87260634770b2d0e97f867f699 has fixed it

**Comment by Tandoy** [comment]
> The commit [c73dd08](https://github.com/wgzhao/Addax/commit/c73dd08332324a87260634770b2d0e97f867f699) has fixed it
got it
