### ISSUE TITLE
关于greenplum insert提升

### ISSUE THREAD

**Issue by cxin-william** [wgzhao/Addax#453]
(1)全局死锁检测开关(需重启数据库)
在Greenplum 6中其默认关闭，需要打开它才可以支持并发更新/删除操作；
gpconfig -c gp_enable_global_deadlock_detector -v on

(2) 禁用GPORCA优化器(GPDB6默认的优化器为：GPORCA)
set optimizer=off;

(3)关闭日志(全局配置参数)
此GUC减少不必要的日志，避免日志输出对I/O性能的干扰。
gpconfig -c log_statement -v none
greenplum6.x版本，直接做insert操作，加一下这三个，效率能提升好多，有空可以研究一下，兄弟
![企业微信截图_16378097982934](https://user-images.githubusercontent.com/66359848/143373397-a09e7b8c-530a-4055-9974-a57b54b46aad.png)

**Comment by wgzhao** [comment]
感谢反馈
