### ISSUE TITLE
[Bug]: 4.0.6版本编译报错

### ISSUE THREAD

**Issue by XhivaW** [wgzhao/Addax#454]
### What happened?

按说明使用`mvn clean package`命令编译时，`clickhouse-reader`模块报错，提示：`Could not resolve dependencies for project com.wgzhao.addax:clickhousereader:jar:4.0.6: Could not find artifact com.github.RoaringBitmap:RoaringBitmap:jar:0.9.9 in dm` 在maven仓库搜索 似乎`org.roaringbitmap.RoaringBitmap`这个使用者更多 Clickhouse官方也支持 建议修改一下依赖

又：issue里的version最高只到4.0.4 : )

### Version

4.0.4 (Default)

### OS Type

Linux (Default)

### Java JDK Version

Oracle JDK 1.8.0

**Comment by XhivaW** [comment]
发现似乎自己搞错了。。

**Comment by wgzhao** [comment]
clickhouse jdbc 驱动是依赖的官方版本

```xml
  <dependency>
      <groupId>ru.yandex.clickhouse</groupId>
      <artifactId>clickhouse-jdbc</artifactId>
      <version>${clickhouse.jdbc.version}</version>
  </dependency>
```
