### ISSUE TITLE
[WIP]:  Add web ui for addax

### ISSUE THREAD

**Issue by xbkaishui** [wgzhao/Addax#464]
### Contact Details（联系人）

308549247@qq.com

### What happened?

should I add a web ui for addax ? 
should contains below feature: 
api for submit job and query status by http rest api
web-ui to management jobs

### Version

4.0.6 (Default)

### Java JDK Version

Oracle JDK 1.8.0

**Comment by wgzhao** [comment]
The project [addax-admin](https://github.com/wgzhao/addax-admin)  is addax-base web ui mangement, it is still in development.

Of course, there are many excellent datax-based web management tools in the community, and it is also suitable for addax

**Comment by xbkaishui** [comment]
Great I will check it

**Comment by baisui1981** [comment]
That's a good idea , May be you can develop it base on [datax-web](https://github.com/WeiYe-Jing/datax-web)?
