### ISSUE TITLE
[Bug]: why there is no hive/reader writer 

### ISSUE THREAD

**Issue by xbkaishui** [wgzhao/Addax#468]
### What happened?

I am just wonder, why there is no hive/reader writer?  I saw the original datax repo include hive reader and writer 
thanks

### Version

4.0.6 (Default)

### Java JDK Version

Oracle JDK 1.8.0

**Comment by wgzhao** [comment]
The original DataX DOES NOT have a hive-related reader/writer plugin
In fact, if you look carefully at the documentation, you will find that the hive reader and writer plug-ins described in the documentation are actually hdfs reader and writer plug-ins。
I have implemented the hive reader plug-in, you can [refer to this document](https://wgzhao.github.io/Addax/4.0.7/reader/hivereader/) 
The reason that did not implement the hive writer plug-in is it's extrem slow  using  `insert into`  to write hive table, so most of the ETL does not use the hive jdbc connection to write data, but directly to the HDFS layer, and then create the corresponding schema on the hive

**Comment by xbkaishui** [comment]
Yes, I agree. in our inside, I just use thrift jdbc to save hive table. it's too slow.  
is there any better ways ?
