### ISSUE TITLE
Kudureader cannot read NaN, -infinity, +Infinity of double, float, demical data types

### ISSUE THREAD

**Issue by niexiongchao** [wgzhao/Addax#471]
### Contact Details（联系人）

niexiongchao@foxmail.com

### What happened?

Kudureader cannot read NaN, -infinity, +Infinity of double, float, demical data types.
The reason is that these three values cannot be converted when converted to Bigdemical, resulting in an error. The solution is to convert these three types to string type。

### Version

4.0.6 (Default)

### OS Type

Linux (Default)

### Java JDK Version

Oracle JDK 1.8.0

### Relevant log output

```shell
No log！it had been fixed in my project
```

**Comment by niexiongchao** [comment]
Unable to submit modified code due to company network restrictions! Hope the author can fix it in time

**Comment by wgzhao** [comment]
I will fix it
