### ISSUE TITLE
[enhancement]: Integrated into starrockswriter

### ISSUE THREAD

**Issue by niexiongchao** [wgzhao/Addax#473]
### Contact Details（联系人）

niexiongchao@foxmail.com

### What happened?

Starrocks is a new and popular MPP database. We hope to support writing to this database. Currently, the corresponding Writer plug-in is officially available, which can be integrated. I have integrated this plugin in the local test, the effect is good! Plug-in reference address: https://github.com/StarRocks/DataX

### Version

4.0.6 (Default)

### OS Type

Linux (Default)

### Java JDK Version

Oracle JDK 1.8.0

**Comment by wgzhao** [comment]
Thanks for your advise
I will integrate ASAP
