### ISSUE TITLE
[Bug]: 对低版本hive+hadoop环境支持问题

### ISSUE THREAD

**Issue by XhivaW** [wgzhao/Addax#483]
### What happened?

Addax使用4.0.7版本 （github的issue页不知道为啥只能选择到4.0.6

CentOS 7 + JDK 1.8

CDH 5.14环境 hive版本1.1.0 hadoop版本2.6.0

如使用发布版hivereader，报错：
```bash
2021-12-29 16:05:48.388 [       job-0] ERROR DBUtil               - test connection of [jdbc:hive2://XXXXXXX:10000/XXXXXXX;AuthMech=3] failed, for Code:[DBUtilErrorCode-10], Description:[连接数据库失败. 请检查您的账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).].  -  具体错误信息为：
java.sql.SQLException: Cannot create PoolableConnectionFactory (Could not open client transport with JDBC Uri: jdbc:hive2://XXXXXXX:10000/XXXXXXX;AuthMech=3: Could not establish connection to jdbc:hive2://XXXXXXX:10000/XXXXXXX;AuthMech=3: 
Required field 'client_protocol' is unset! Struct:TOpenSessionReq(client_protocol:null, configuration:{set:hiveconf:hive.server2.thrift.resultset.default.fetch.size=1000, use:database=XXXX})).
```

应该是默认hive-jdbc版本与server版本不一致导致 尝试修改pom文件中hive-jdbc版本 编译报错无对应apache版本 查看发现当前Addax的apache环境使用io.trino.apache.hadoop 似乎不支持2.X版本

如使用发布版rdbmreader，hive-jdbc驱动正常配置的情况下，报错：
```bash
2021-12-29 16:10:53.603 [       job-0] ERROR DBUtil               - test connection of [jdbc:hive2://XXXXXXX:10000/XXXXXX;AuthMech=3] failed, for Code:[DBUtilErrorCode-10], Description:[连接数据库失败. 请检查您的账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).].  -  具体错误信息为：
java.lang.IllegalArgumentException: Unrecognized Hadoop major version number: 3.2.0.
```
应该也是Addax使用自带apache环境 与hivereader面临一样的问题

想咨询下是否有解决方法？

### Version

4.0.6 (Default)

### OS Type

Linux (Default)

### Java JDK Version

Oracle JDK 1.8.0

**Comment by wgzhao** [comment]
这个版本的确有点低
要解决这个问题，要把依赖 `io.trino.hadoop`转为依赖hadoop的原生jar包，然后就可以针对特定组件进行降级

**Comment by XhivaW** [comment]
> 这个版本的确有点低 要解决这个问题，要把依赖 `io.trino.hadoop`转为依赖hadoop的原生jar包，然后就可以针对特定组件进行降级

好的 这部分我自己尝试替换修改下 谢谢

**Comment by wgzhao** [comment]
我也会尝试，之前在原生和trino版本之间切换过几次。

**Comment by wgzhao** [comment]
你可以尝试下载我重新编译的版本，其中hadoop的版本为2.6.0, hive-jdbc 的版本为 1.1.0

https://pan.baidu.com/s/1YyBuzZenPp-jI2j_RhPX9Q 提取码: bxeu

**Comment by XhivaW** [comment]
> 你可以尝试下载我重新编译的版本，其中hadoop的版本为2.6.0, hive-jdbc 的版本为 1.1.0
> 
> https://pan.baidu.com/s/1YyBuzZenPp-jI2j_RhPX9Q 提取码: bxeu

测试了下 报了连接失败 不过apache环境和jdbc版本应该没问题了 辛苦作者

**Comment by wgzhao** [comment]
当前 master 分支已经移除了 trino 的依赖，参考 #523
