### ISSUE TITLE
[Bug]: 关于数据类型转换的问题

### ISSUE THREAD

**Issue by XhivaW** [wgzhao/Addax#486]
### What happened?

Addax: 4.0.7
CentOS 7 + JDK 1.8

如果hive表中定义特定字段为decimal 使用hdfsreader读取的时候 无论是使用Long还是Double 都会报错 请问这个问题有解决方案吗？

### Version

4.0.7

### OS Type

Linux (Default)

### Java JDK Version

Oracle JDK 1.8.0

**Comment by wgzhao** [comment]
这个可以解决，麻烦给出一个你实际测试配置文件给我，然后贴出具体的错误信息

**Comment by XhivaW** [comment]
> 这个可以解决，麻烦给出一个你实际测试配置文件给我，然后贴出具体的错误信息

似乎不是decimal的问题 测试了一下感觉是内部数据类型转换出的错 我先多测试几次整理下 重新发个issue 作者辛苦了
