### ISSUE TITLE
[Improvement]: Task fault tolerance and breakpoint resume

### ISSUE THREAD

**Issue by Tandoy** [wgzhao/Addax#506]
### Contact Details（联系人）

tangzhi1318@163.com

### What happened?

If the source and sink are disconnected or a task fails, there is a retry mechanism: 
1. Save the number of successful records extracted by each task to redis or zk, and then adjust the querySql in the json file to restart the task. 
2. And record the primary key offset to ensure job idempotency

### Version

4.0.2

### OS Type

Linux (Default)

### Java JDK Version

Oracle JDK 1.8.0

**Comment by wgzhao** [comment]
这个不应该在 ETL 工具里实现，应该另有一个机制来做这件事情。
而且获取的数据是无序的，你没有一个唯一的偏移来记录上次执行的位置。
