### ISSUE TITLE
[feat]:请支持一下kafka、pulsar实时数据接入和分发 

### ISSUE THREAD

**Issue by zyclove** [wgzhao/Addax#516]
### Contact Details（联系人）

zyc2012518@126.com

### What happened?

当前简单数据接入和转发涉及到消息流方式，请支持一下kafka、pulsar实时数据接入和分发 

### Version

4.0.8 (Default)

### Java JDK Version

Oracle JDK 1.8.0

**Comment by wgzhao** [comment]
写入 Kafka 已基本支持

**Comment by zyclove** [comment]
@wgzhao 太好了，还请大家一起抽点时间把kafka消费支持一下，谢谢
