### ISSUE TITLE
clickhouseReader 读失败 

### ISSUE THREAD

**Issue by han-a1** [wgzhao/Addax#547]
### Contact Details（联系人）

174159677@qq.com

### What happened?

从clickhouse中全量同步到influxdb报错，如果限制clickhouse的SQL查询行数limit就不报错

### Version

4.0.8 (Default)

### OS Type

Linux (Default)

### Java JDK Version

Oracle JDK 1.8.0

### Relevant log output

```shell
配置的 column/table/where/querySql或者向 DBA 寻求帮助.].  - 执行的SQL为: select CollectTime, SiteID, AreaID, PointID, SensorID, MonitoringTypeID, MonitoringData from test_data 具体错误信息为：java.lang.IllegalArgumentException: boolean(52) should between 0 and 1 inclusive of both values
        at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:50)
        at com.wgzhao.addax.rdbms.util.RdbmsException.asQueryException(RdbmsException.java:45)
        at com.wgzhao.addax.rdbms.reader.CommonRdbmsReader$Task.startRead(CommonRdbmsReader.java:248)
        at com.wgzhao.addax.plugin.reader.clickhousereader.ClickHouseReader$Task.startRead(ClickHouseReader.java:138)
        at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by wgzhao** [comment]
请给出完整的 json 文件和日志内容

**Comment by han-a1** [comment]
> 请给出完整的 json 文件和日志内容

{
  "job": {
    "setting": {
      "speed": {
        "channel": 4
      },
      "errorLimit": {
        "record": 0,
        "percentage": 0.02
      }
    },
    "content": [
      {
        "reader": {
          "name": "clickhousereader",
          "parameter": {
            "username": "default",
            "password": "123456",
            "connection": [
              {
                "jdbcUrl": [
                  "jdbc:clickhouse://10.73.7.10:8123/default"
                ],
                "querySql": [
                  "select CollectTime, SiteID, AreaID, PointID, SensorID, MonitoringTypeID, MonitoringData from test_data "
                ]
              }
            ]
          }
        },
        "writer": {
          "name": "influxdbwriter",
          "parameter": {
            "username": "root",
	    "password": "123456",
	    "column": [
		    {"name": "time", "type": "timestamp"},
		    {"name": "site_id", "type": "TAG"},
		    {"name": "area_id", "type": "TAG"},
		    {"name": "point_id", "type": "TAG"},
		    {"name": "sensor_id", "type": "TAG"},
		    {"name": "monitoring_type_id", "type": "TAG"},
		    {"name": "monitoring_data", "type": "double"}
	    ],
		 "preSql": [
            "delete from sensor_data"
          ],
	    "connection": [
              {
		"endpoint": "http://10.73.7.10:8086",
		"database": "dh_iot",
		"table": "sensor_data"
	      }
	    ],
	    "connTimeout": 15,
	    "readTimeout": 20,
	    "writeTimeout": 20,
	    "batchSize": "1024"
          }
        }
      }
    ]
  }
}

**Comment by wgzhao** [comment]
这应该不是有没有 limit  的问题，从你仅有发出来的错误信息来看，是数据类型和数据内容不匹配导致的。
