### ISSUE TITLE
[Bug]: 在使用HiveReader时报错

### ISSUE THREAD

**Issue by Soulmate76** [wgzhao/Addax#568]
### What happened?

hiveReader clickhousewriter
hadoop version：cdh 3.0.0
报错：java.lang.NoClassDefFoundError: org/apache/commons/configuration/Configuration
1.我从hivereader idea iml文件中确实有打包hadoop 2.7.1，但是我没找到这个版本在哪里设置的,
我想的是把版本换到3.0试试。
2.hivereader基于rdbmsreader,如果是这样,那rdbms读取hive是否 也会失败
着急！！！ 希望大佬早点回复~
3.在使用rdbms读取Hive时需要账号密码,但是我hive并没有设置,这个可以规避吗

### Version

4.0.8 (Default)

### OS Type

Linux (Default)

### Java JDK Version

Oracle JDK 1.8.0

**Comment by Soulmate76** [comment]
已解决 少jar

**Comment by ekeyme** [comment]
> commons-configuration2-2.7

你是手动导包么？
