### ISSUE TITLE
[Bug]: hive reader null值问题

### ISSUE THREAD

**Issue by Soulmate76** [wgzhao/Addax#571]
### Contact Details（联系人）

2580981190@qq.com

### What happened?

addax读取Hive表时，表中数据存在null值，把数据存入clickhouse时报nullpointerException，必须要以sql case when的形式，将null转为空字符串数据才能够存入，但表中数据列几十个，每一个都需要做case when转换，请问有什么好的解决方案吗？

### Version

4.0.8 (Default)

### OS Type

Linux (Default)

### Java JDK Version

Oracle JDK 1.8.0

**Comment by wgzhao** [comment]
尝试在clickhouse 对应字段加上 nullable 属性试试
具体创建可以参考 https://clickhouse.com/docs/en/sql-reference/data-types/nullable/

**Comment by Soulmate76** [comment]
> 尝试在 clickhouse 尝试设置可以为空的属性 具体可以创建参考https://clickhouse.com/docs/en/sql-reference/data-types/nullable/
