### ISSUE TITLE
[Bug]: Doris插件加载失败

### ISSUE THREAD

**Issue by redgreat** [wgzhao/Addax#572]
### Contact Details（联系人）

rubygreat@msn.com

### What happened?

sh addax.sh ../job/test.json
python addax.py ../job/test.json
报同样的错误

vim ../job/test.json
`{
  "job": {
    "content": [
      {
        "reader": {
          "name": "mysqlreader",
          "parameter": {
            "username": "***",
            "password": "***",
            "column": [
              "*"
            ],
            "splitPk": "id",
            "connection": [
              {
                "table": [
                  "*"
                ],
                "jdbcUrl": [
                  "jdbc:mysql://*:3306/*"
                ]
              }
            ]
          }
        },
        "writer": {
          "name": "doriswriter",
          "parameter": {
            "endpoint": "http://*:8030/",
            "username": "*",
            "password": "*",
            "database": "*",
            "table": "*",
            "column": [
              "*"
            ],
            "postSql": [],
            "preSql": [],
            "loadProps": {
            },
            "maxBatchRows" : 500000,
            "maxBatchByteSize" : 104857600,
            "labelPrefix": [],
            "lineDelimiter": "\n"
          }
        }
      }
    ],
    "setting": {
      "speed": {
        "channel": 1
      }
    }
  }
}
`

### Version

4.0.8 (Default)

### OS Type

Linux (Default)

### Java JDK Version

Oracle JDK 1.8.0

### Relevant log output

```shell
___      _     _            
 / _ \    | |   | |           
/ /_\ \ __| | __| | __ ___  __
|  _  |/ _` |/ _` |/ _` \ \/ /
| | | | (_| | (_| | (_| |>  < 
\_| |_/\__,_|\__,_|\__,_/_/\_\

:: Addax version ::    (v4.0.8)

2022-05-24 18:34:34.782 [        main] WARN  ConfigParser         - 插件[mysqlreader,doriswriter]加载失败，1s后重试... Exception:Code:[Framework-12], Description:[Addax 插件初始化错误, 该问题通常是由于Addax 安装错误引起，请联系您的运维解决 .].  - 插件加载失败，未完成指定插件加载:[doriswriter, mysqlreader] 
com.wgzhao.addax.common.exception.AddaxException: Code:[Framework-12], Description:[Addax 插件初始化错误, 该问题通常是由于Addax 安装错误引起，请联系您的运维解决 .].  - 插件加载失败，未完成指定插件加载:[doriswriter, mysqlreader]
        at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:50)
        at com.wgzhao.addax.core.util.ConfigParser.parsePluginConfig(ConfigParser.java:189)
        at com.wgzhao.addax.core.util.ConfigParser.parse(ConfigParser.java:89)
        at com.wgzhao.addax.core.Engine.entry(Engine.java:115)
        at com.wgzhao.addax.core.Engine.main(Engine.java:163)
```

**Comment by redgreat** [comment]
在安装脚本里直接下载安装包后解压使用的
https://github.com/wgzhao/Addax/releases/download/4.0.8/addax-4.0.8.tar.gz

**Comment by redgreat** [comment]
文件夹权限也加了，是用root用户执行的
`[root@iZbp1e4qug6kl2vcvhr5f2Z writer]# ls -l
total 0
drwxr-xr-x 3 root root 102 Jan  9 13:56 cassandrawriter
drwxr-xr-x 3 root root 103 Jan  9 13:56 clickhousewriter
drwxr-xr-x 3 root root  96 Jan  9 13:56 dbfwriter
drwxr-xr-x 3 root root 104 Jan  9 13:56 elasticsearchwriter
drwxr-xr-x 3 root root  98 Jan  9 13:56 excelwriter
drwxr-xr-x 3 root root  96 Jan  9 13:56 ftpwriter
drwxr-xr-x 3 root root 102 Jan  9 13:56 greenplumwriter
drwxr-xr-x 3 root root 104 Jan  9 13:56 hbase11xsqlwriter
drwxr-xr-x 3 root root 101 Jan  9 13:56 hbase11xwriter
drwxr-xr-x 3 root root 104 Jan  9 13:56 hbase20xsqlwriter
drwxr-xr-x 3 root root  97 Jan  9 13:56 hdfswriter
drwxr-xr-x 3 root root 102 Jan  9 13:56 influxdb2writer
drwxr-xr-x 3 root root 101 Jan  9 13:56 influxdbwriter
drwxr-xr-x 3 root root  97 Jan  9 13:56 kuduwriter
drwxr-xr-x 3 root root 100 Jan  9 13:56 mongodbwriter
drwxr-xr-x 3 root root  98 Jan  9 13:56 mysqlwriter
drwxr-xr-x 3 root root  99 Jan  9 13:56 oraclewriter
drwxr-xr-x 3 root root 103 Jan  9 13:56 postgresqlwriter
drwxr-xr-x 3 root root  98 Jan  9 13:56 rdbmswriter
drwxr-xr-x 3 root root  98 Jan  9 13:56 rediswriter
drwxr-xr-x 3 root root  99 Jan  9 13:56 sqlitewriter
drwxr-xr-x 3 root root 102 Jan  9 13:56 sqlserverwriter
drwxr-xr-x 3 root root  99 Jan  9 13:56 streamwriter
drwxr-xr-x 3 root root 101 Jan  9 13:56 tdenginewriter
drwxr-xr-x 3 root root 100 Jan  9 13:56 txtfilewriter
[root@iZbp1e4qug6kl2vcvhr5f2Z writer]# pwd
/opt/addax/plugin/writer`

**Comment by imdevboy** [comment]
我也遇到这个问题，怎么解决的？

**Comment by wgzhao** [comment]
请将项目的压缩文件解压到 `plugin/writer` 目录下，然后再执行

[doriswriter.zip](https://github.com/wgzhao/Addax/files/8792531/doriswriter.zip)
