### ISSUE TITLE
[Bug]: DolphinScheduler调度addax日志显示不正常

### ISSUE THREAD

**Issue by imzhf** [wgzhao/Addax#576]
### What happened?

DolphinScheduler通过shell方式调用addax，日志中的日期部分显示不正常，如下所示：

![image](https://user-images.githubusercontent.com/3370207/171146235-d7920621-5ac2-4694-8380-e62b2d1bb8dd.png)

### Version

4.0.8 (Default)

### Java JDK Version

Oracle JDK 1.8.0

**Comment by wgzhao** [comment]
addax.py 脚本已经废弃不再维护了
