### ISSUE TITLE
[Bug]: addax.sh的输出重定向到文件中，部分字符显示为乱码

### ISSUE THREAD

**Issue by imzhf** [wgzhao/Addax#580]
### What happened?

调用：
![image](https://user-images.githubusercontent.com/3370207/171547251-7e418062-67e8-4081-81b6-c75096b70ad1.png)
文件中看到的内容：
![image](https://user-images.githubusercontent.com/3370207/171547374-a20649c6-3784-4fb2-a570-fe47bd4c1ffb.png)

### Version

4.0.8 (Default)

### Java JDK Version

Oracle JDK 1.8.0

**Comment by imzhf** [comment]
完成日志文件：
[UcDict.log](https://github.com/wgzhao/Addax/files/8820513/UcDict.log)

**Comment by imzhf** [comment]
也不影响使用，主要是看着不美观

**Comment by imzhf** [comment]
控制台看不到乱码，重定向到文件中，才看到日期部分字符乱码

**Comment by wgzhao** [comment]
这个不是乱码，是控制字符，用于终端彩色输出。如果你查看 Addax 的日志文件，是没有这些内容的，这仅仅在终端输出才会有。
如果不希望终端有些控制字符的输出，可以修改 `conf/logback.xml` 文件的第 28 行

`%cyan(%d{yyyy-MM-dd HH:mm:ss.SSS}) %green([%12thread]) %highlight(%-5level) %magenta(%-20logger{0}) - %msg%n`
改成如下
`%d{yyyy-MM-dd HH:mm:ss.SSS} [%12thread] %-5level %-20logger{0} - %msg%n` 
即可

**Comment by imzhf** [comment]
收到，明白了

**Comment by imzhf** [comment]
dolphinscheduler调度工具调用addax时，应该是把控制台输出重定向到文件，在dolphinscheduler调度工具中看到的日志，就是重定向后的，所以才会出现颜色控制字符无法正常显示的问题。
