### ISSUE TITLE
[Bug]: MySQL数据同步到hdfs时，写parquet文件，时间错误

### ISSUE THREAD

**Issue by nettm** [wgzhao/Addax#621]
### What happened?

同步MySQL数据到hdfs，写parquet文件形式，发现时间不一致，MySQL数据库时间为2022-07-21 16:52:32，写到parquet后，时间变为1970-01-20 04:39:53.552000+00:00，经对源码的调查，发现是HdfsHelper中transportParRecord函数中对时间戳进行了除1000的操作导致的，改为builder.set(colName, column.asLong());后，数据一致。

### Version

4.0.8

### OS Type

Linux (Default)

### Java JDK Version

Oracle JDK 1.8.0

**Comment by wgzhao** [comment]
感谢反馈

**Comment by EvanCsw** [comment]
> 你好 请问方便提供一下使用的json及对应parquet表的建表语句参考下吗？我这里timestamp写入parquet一直无法识别

我觉得他这个不可能写入后能够识别。因为存入的类型应该是int96而不是long
