### ISSUE TITLE
[Bug]: 外部数据导入redis

### ISSUE THREAD

**Issue by JKwanghao** [wgzhao/Addax#629]
### Contact Details（联系人）

969124128@qq.com

### What happened?

目前这个rediswirter好像从介绍来看，只支持redis reader的过滤？  外部数据，比如mysql数据如何导入redis？ 好像没有插件支持

### Version

4.0.9 (Default)

### OS Type

Linux (Default)

### Java JDK Version

Oracle JDK 1.8.0

**Comment by wgzhao** [comment]
谢谢反馈
不过这个我没有想好 RDBMS 的表如何和 redis 的数据对应起来

比如一个表有三个字段，共 10 条记录，这些数据应该已什么样的方式存在 redis 中
