### ISSUE TITLE
[Bug]: transforer可以获取源表列名吗，使用rmdb读取trino的表

### ISSUE THREAD

**Issue by ShawshankLin** [wgzhao/Addax#639]
### What happened?

transforer可以获取源表列名吗，使用rmdb读取trino的表

在自定义transformer时，怎么通过record获取源表的列名呢，或者通过其他方法可以获取到呢
![image](https://user-images.githubusercontent.com/16248686/190898489-b2416246-a2be-4586-ac51-81bcba23e3a7.png)

### Version

4.0.9 (Default)

### OS Type

Windows

### Java JDK Version

Oracle JDK 1.8.0

**Comment by wgzhao** [comment]
record 里并没有记录列名，所以暂时还没有办法在 transformer 这层传递列名过去

**Comment by ShawshankLin** [comment]
> record 里并没有记录列名，所以暂时还没有办法在 transformer 这层传递列名过去

嗯嗯，改了下代码，从resultset那里把name加到column，待下去
