### ISSUE TITLE
【feat】支持datax on yarn 分布式server，任务管理提交

### ISSUE THREAD

**Issue by zyclove** [wgzhao/Addax#668]
参照这两个不错的项目，支持datax-on-yarn 任务提交
https://github.com/duhanmin/datax-on-yarn
https://github.com/TianLangStudio/DataXServer
提供远程多语言调用（ThriftServer，HttpServer） 分布式运行（DataX on YARN） 功能

**Comment by zyclove** [comment]
请问这个有计划吗？能否支持一下，提升相比datax本身优势，吸引更多开发者加入。

**Comment by wgzhao** [comment]
很抱歉，暂不考虑

**Comment by zhangyinghahaha** [comment]
这个问题可以用xxl-job搭个命令行任务执行器，就可以实现任务调度，不用本地单机执行

**Comment by zyclove** [comment]
> 

可以提供一个样例吗？谢谢

**Comment by zhangyinghahaha** [comment]
@zyclove xxl-job注册一个命令行的执行器就行了，比较完善的方案可以参考一下datax-web
