### ISSUE TITLE
[求助]请问还维护吗？我这边influxdb读取数据报错

### ISSUE THREAD

**Issue by lingchaoa** [wgzhao/Addax#714]
### What happened?

A bug happened!

### Version

4.0.10 (Default)

### Java JDK Version

Oracle JDK 1.8.0

**Comment by lingchaoa** [comment]
com.wgzhao.addax.common.exception.AddaxException: Code:[Framework-02], Description:[Addax 引擎运行过程出错，具体原因请参看Addax 运行结束时的错误诊断信息  .].  - 找到plugin[influxdbreader]的Job配置. - java.lang.ClassCastException: com.zyt.datax.plugin.reader.influxdbreader.InfluxDBReader$Job cannot be cast to com.wgzhao.addax.common.plugin.AbstractJobPlugin

**Comment by wgzhao** [comment]
>java.lang.ClassCastException: com.zyt.datax.plugin.reader.influxdbreader.InfluxDBReader$Job cannot be cast to 

从这个报错信息来看，这个插件不是 Addax 提供了，请直接从项目下载源代码编译或者预编译好的二进制文件进行测试。

**Comment by lingchaoa** [comment]
报错原因是一样的，还请帮忙看一下。
**com.wgzhao.addax.common.exception.AddaxException: Code:[Framework-02], Description:[Addax 引擎运行过程出错，具体原因请参看Addaang.ClassCastException: com.alibaba.datax.plugin.reader.influxdbreader.InfluxDBReader$Job cannot be cast to com.wgzhao.addax.common.plugin.AbstractJobPlugin。**

**Comment by wgzhao** [comment]
>Addaang.ClassCastException: com.alibaba.datax.plugin.reader.influxdbreader.InfluxDBReader$Job

这边的插件包前缀不是 `com.alibaba.datax`，你可以向 [DataX](https://github.com/alibaba/datax)  反馈此问题
