### ISSUE TITLE
[Bug]: oraclereader- data accuracy problem when oracle field type is number

### ISSUE THREAD

**Issue by QJG666** [wgzhao/Addax#789]
### What happened?

Basic environment
- jdk.18
- addax-4.0.13-snapshot

When reading data with field type number in oracle, the accuracy of the data is changed during the internal type conversion of addax.

data in the oracle database:
```text
0.833333482887588
```
---
data in the hive warehouse:
```text
8.33333482887588027634313065556670386656E-01
```

### Version

4.0.12 (Default)

### OS Type

Linux (Default)

### Java JDK Version

Oracle JDK 1.8.0

**Comment by wgzhao** [comment]
Please provide the contents of the JSON configuration file for running the task, as well as the complete output log during runtime.

**Comment by QJG666** [comment]
Sorry for not replying to your message in time.
That is, when I synchronize data for the oracle field type number, addax internally displays the data in scientific notation. I also did not add to_char to the field of type number in the json file, nor did the log print error during execution.
