### ISSUE TITLE
[Bug]: oracle数据库blob与blob字段传输

### ISSUE THREAD

**Issue by weihebu** [wgzhao/Addax#823]
### What happened?

测试发现，当oracle数据库表中存在blob字段时，即便目标表有对应的blob字段，执行传输任务会报错。
错误为，ORA-03106 : two-task communication protocal error
网上查阅了一些资料，但仍旧不知道怎么解决这个问题，请问作者有什么办法吗？
我看blob字段也确实顺利转成bytes了。

### Version

4.0.12 (Default)

### OS Type

Linux (Default)

### Java JDK Version

Oracle JDK 1.8.0

**Comment by weihebu** [comment]
我下午又重新测试了一下，如果时insert状态是完全没有问题的。但是使用update(id) 这样方式就会报ORA-03106 : fatal two-task communication protocal error,我在想是不是oracle 自身的merge into 语法不支持blob字段的写入？

**Comment by wgzhao** [comment]
可以尝试把 merge into 语句直接在 Oracle 上执行看看是否报错
