### ISSUE TITLE
[Bug]: 执行bin/addax.sh job/test.json 报错：没有那个文件或目录

### ISSUE THREAD

**Issue by PittYao** [wgzhao/Addax#851]
### What happened?

1. 拉取master分支代码，在windows上编译，windows上有py3.10环境，按照如下编译
`mvn clean package
mvn package assembly:single`
2.编译后将 target/addax-4.1.2-SNAPSHOT 压缩上传到centos服务器，执行示例文档中的test.json。报错:没有那个文件或目录。但job/test.json文件是存在的
`
bin/addax.sh job/test.json `

![image](https://github.com/wgzhao/Addax/assets/26101917/ff3d8a7e-03bb-466e-aea1-75de69c95670)

### Version

4.1.1 (Default)

### OS Type

Linux (Default)

### Java JDK Version

Oracle JDK 1.8.0

**Comment by wgzhao** [comment]
上面的提示是表示 ./bin/addax.sh 这个脚本的换行格式已经被换成了 Windows 的 `\r\n` 模式，你需要在编辑器中打开改文件，重新保存，且换行形式换成 `\n` 模式即可。

**Comment by PittYao** [comment]
> 上面的提示是表示 ./bin/addax.sh 这个脚本的换行格式已经被换成了 Windows 的 `\r\n` 模式，你需要在编辑器中打开改文件，重新保存，且换行形式换成 `\n` 模式即可。

OK Liunx 执行替换命令即可运行
`
find addax.sh -type f -print0 | xargs -0 sed -i "s/\r//g"
`
