### ISSUE TITLE
[Bug]: 你好 是否必须要先在输出端先建表才能使用

### ISSUE THREAD

**Issue by PittYao** [wgzhao/Addax#853]
### What happened?

![image](https://github.com/wgzhao/Addax/assets/26101917/b9c4c7fe-fdf5-4508-8840-cf5d1ad65da3)
如题

### Version

4.1.1 (Default)

### OS Type

Linux (Default)

### Java JDK Version

Oracle JDK 1.8.0

**Comment by wgzhao** [comment]
是的，Addax 只负责采集，不做其他额外的工作

**Comment by PittYao** [comment]
> 是的，Addax 只负责采集，不做其他额外的工作

好的，这里是否有web端可视化任务执行的计划，还有addax和datax一样也是只能单机运行是吗

**Comment by wgzhao** [comment]
> > 是的，Addax 只负责采集，不做其他额外的工作
> 
> 好的，这里是否有web端可视化任务执行的计划，还有addax和datax一样也是只能单机运行是吗

1. 暂无图形化界面，目前只能通过命令行运行，但应该和市场已有的 web 端的可视化可以集成
2. Addax 默认是单机运行，但可以通过现有的调度来做到分布式执行，目前我司就是用的这种方式

**Comment by PittYao** [comment]
> > > 是的，Addax 只负责采集，不做其他额外的工作
> > 
> > 
> > 好的，这里是否有web端可视化任务执行的计划，还有addax和datax一样也是只能单机运行是吗
> 
> 1. 暂无图形化界面，目前只能通过命令行运行，但应该和市场已有的 web 端的可视化可以集成
> 2. Addax 默认是单机运行，但可以通过现有的调度来做到分布式执行，目前我司就是用的这种方式

感谢解答，还有几个问题
1.这里分布式是指两个机器上运行单独的两个不同的任务，还是两个机器分别执行一个任务中的一部分.
2.还有增量同步也是靠querySql中的time字段来同步吗
3.支持arm芯片的服务器运行吗

**Comment by wgzhao** [comment]
> 1.这里分布式是指两个机器上运行单独的两个不同的任务，还是两个机器分别执行一个任务中的一部分.
执行不同的任务，一个任务是最小单位，目前不可分割
> 2.还有增量同步也是靠querySql中的time字段来同步吗
Addax 本身并不支持增量同步，如果要达到此目标，需要结合数据表结构，数据增加情况，然后结合 `querySql` 来实现，但这个无担保性
> 3.支持arm芯片的服务器运行吗
理论上只要用支持 ARM 的 JDK 来编译应该是可以运行的，但我没有尝试过。

**Comment by PittYao** [comment]
> > 1.这里分布式是指两个机器上运行单独的两个不同的任务，还是两个机器分别执行一个任务中的一部分.
> 
> 执行不同的任务，一个任务是最小单位，目前不可分割
> 
> > 2.还有增量同步也是靠querySql中的time字段来同步吗
> 
> Addax 本身并不支持增量同步，如果要达到此目标，需要结合数据表结构，数据增加情况，然后结合 `querySql` 来实现，但这个无担保性
> 
> > 3.支持arm芯片的服务器运行吗
> 
> 理论上只要用支持 ARM 的 JDK 来编译应该是可以运行的，但我没有尝试过。

感谢解答 有问题再咨询

**Comment by czxin788** [comment]
我想用AB表切换的方式，同步数据到目标表：
过程如下：
1、在目标库建立临时表 create table t_tmp;
2、insert into t_tmp;
3、alter table t rename to t_bak;
4、alter table t_tmp rename to t;
5、drop table t_bak;
但是遗憾的是，不论是datax还是addax，presql都不是最先执行的，需要先检查connection对应的表是否存在，然后才执行presql
```
  ],
                        "preSql": [
                          "create table t_tmp like t"
                        ],
                        "connection": [
                            {
                                "jdbcUrl": "jdbc:mysql://xxxx,
                                "table": [
                                    "t_tmp"
                                ]
                            }
                        ],
```
