### ISSUE TITLE
[Bug]: channel描述是不是有点问题

### ISSUE THREAD

**Issue by sdhzwc** [wgzhao/Addax#923]
### What happened?

![image](https://github.com/wgzhao/Addax/assets/46134044/eff3241a-273b-4936-9d5b-71dabec69c6c)

默认 每个taskgroup对应5个channel 也相当于5个并发（也相当于5个线程）, speed.channel=3 我的理解不到一个taskgroup,也等于3个线程 而不是15个 如果不对的话 还请指正（B站别的课程教的）

### Version

4.1.1 (Default)

### Java JDK Version

Oracle JDK 1.8.0

**Comment by wgzhao** [comment]
你的理解是对的，`speed.channel` 决定了 Task 的数量， `speed.channel / taskGroup.channel` 决定了 TaskGroup 的数量
