### ISSUE TITLE
Sap Hana组件会支持吗

### ISSUE THREAD

**Issue by sdhzwc** [wgzhao/Addax#975]
### What happened?

新需求

### Version

4.1.3 (Default)

### Java JDK Version

Oracle JDK 1.8.0

**Comment by wgzhao** [comment]
对 SAP HANA 不是太了解，但是我看它支持 JDBC 连接方式，因此理论上可以直接使用 rdbmsreader/rdbmswriter 这样的通用插件来支持。

以读取 HANA 为例，可以通过下面的方式进行测试：

1. 从中央仓库下载符合版本的 JDBC 驱动 [ngdbc-2.8.16](https://repo1.maven.org/maven2/com/sap/cloud/db/jdbc/ngdbc/2.18.16/ngdbc-2.18.16.jar)
2. 将下载的驱动拷贝到 `plugin/reader/rdbmsreader/libs` 目录下
3. 配置类似如下的 json 文件

```json
{
  "job": {
    "setting": {
      "speed": {
        "byte": 1048576,
        "channel": 1
      },
      "errorLimit": {
        "record": 0,
        "percentage": 0.02
      }
    },
    "content": {
      "reader": {
        "name": "rdbmsreader",
        "parameter": {
          "username": "sap",
          "password": "sappassword",
          "column": [
            "*"
          ],
          "driver": "com.sap.db.jdbc.Driver",
          "connection": [
            {
              "table": [
                "default.table"
              ],
              "jdbcUrl": [
                "jdbc:sap://127.0.0.1:30715/test"
              ]
            }
          ],
          "fetchSize": 1024,
          "where": "1 = 1"
        }
      },
      "writer": {
        "name": "streamwriter",
        "parameter": {
          "print": true
        }
      }
    }
  }
}
```

然后进行测试，看是否满足要求。

**Comment by sdhzwc** [comment]
> 对 SAP HANA 不是太了解，但是我看它支持 JDBC 连接方式，因此理论上可以直接使用 rdbmsreader/rdbmswriter 这样的通用插件来支持。
> 
> 
> 
> 以读取 HANA 为例，可以通过下面的方式进行测试：
> 
> 
> 
> 1. 从中央仓库下载符合版本的 JDBC 驱动 [ngdbc-2.8.16](https://repo1.maven.org/maven2/com/sap/cloud/db/jdbc/ngdbc/2.18.16/ngdbc-2.18.16.jar)
> 
> 2. 将下载的驱动拷贝到 `plugin/reader/rdbmsreader/libs` 目录下
> 
> 3. 配置类似如下的 json 文件
> 
> 
> 
> ```json
> 
> {
> 
>   "job": {
> 
>     "setting": {
> 
>       "speed": {
> 
>         "byte": 1048576,
> 
>         "channel": 1
> 
>       },
> 
>       "errorLimit": {
> 
>         "record": 0,
> 
>         "percentage": 0.02
> 
>       }
> 
>     },
> 
>     "content": {
> 
>       "reader": {
> 
>         "name": "rdbmsreader",
> 
>         "parameter": {
> 
>           "username": "sap",
> 
>           "password": "sappassword",
> 
>           "column": [
> 
>             "*"
> 
>           ],
> 
>           "driver": "com.sap.db.jdbc.Driver",
> 
>           "connection": [
> 
>             {
> 
>               "table": [
> 
>                 "default.table"
> 
>               ],
> 
>               "jdbcUrl": [
> 
>                 "jdbc:sap://127.0.0.1:30715/test"
> 
>               ]
> 
>             }
> 
>           ],
> 
>           "fetchSize": 1024,
> 
>           "where": "1 = 1"
> 
>         }
> 
>       },
> 
>       "writer": {
> 
>         "name": "streamwriter",
> 
>         "parameter": {
> 
>           "print": true
> 
>         }
> 
>       }
> 
>     }
> 
>   }
> 
> }
> 
> ```
> 
> 
> 
> 然后进行测试，看是否满足要求。

这个理解是对的，主要是想着单独组件化，datax商业版是支持的，所以想着addax也支持一下，这样组件更全
