### ISSUE TITLE
[Bug]: mysql-分库分表情况下channel无效

### ISSUE THREAD

**Issue by yinlice** [wgzhao/Addax#999]
### What happened?

mysql-分库分表-任务设置了8个实例.每个实例128张表.修改了channel=5和channel=10.15.20.30.40情况下 一直是5个子任务并行执行.每个taskGroup设置的并发量 = 5

### Version

4.1.3 (Default)

### Java JDK Version

Oracle JDK 1.8.0

**Comment by yinlice** [comment]
读mysql

**Comment by wgzhao** [comment]
请贴出完整的任务执行日志

**Comment by yinlice** [comment]
测试发现autoPk:true 分库分表情况下.是串行执行.每次只执行6个子sql(同一张表).执行完了 再执行下一张表,加大channel也是6个线程.
autoPk:false 可以解决.加大channel生效.

**Comment by yinlice** [comment]
Addax version :: (v4.0.9-SNAPSHOT)
